- .gitmodules
close #8 
---
- submodule 생성 및 연결
---
> [Chore] 서브모듈 레포지토리 연결

- build.gradle
- src/test/java/com/yzgeneration/evc/mock/member/FakeEmailVerificationRepository.java
- src/test/java/com/yzgeneration/evc/mock/member/FakeMemberRepository.java
> [Chore] 테스트 깨짐 임시 수정

- src/test/java/com/yzgeneration/evc/member/service/MemberAuthenticationServiceTest.java
> [Chore] 테스트 깨짐

- .gitignore
- META-INF/MANIFEST.MF
- build.gradle
- src/main/resources/META-INF/MANIFEST.MF
> [Fix] 빌드 에러 수정

- .github/workflows/deploy.yml
> [Chore] 설정파일 변경

- .github/workflows/deploy.yml
> [Chore] deploy.yml 오타수정

- src/main/java/com/yzgeneration/evc/common/exception/CustomException.java
- src/main/java/com/yzgeneration/evc/common/exception/CustomExceptionHandler.java
- src/main/java/com/yzgeneration/evc/common/exception/ErrorCode.java
- src/main/java/com/yzgeneration/evc/common/exception/ErrorResponse.java
close #31 
---
- custom error 처리 추가
- error code enum 작성
- custom exception & exceptionhandler 작성
---
> [Feat/#31] Custom 예외처리 추가

- src/main/java/com/yzgeneration/evc/security/JwtAuthenticationFilter.java
> [Fix] 필터 제외 경로 수정

- build.gradle
- src/main/java/com/yzgeneration/evc/security/SecurityConfig.java
close #42
---
- secutiry filter에 cors 정책 추가
---
> [Fix] filter에 cors 정책 추가 #42

- src/main/java/com/yzgeneration/evc/domain/member/authentication/controller/AuthenticationController.java
- src/main/java/com/yzgeneration/evc/domain/member/authentication/dto/AuthenticationResponse.java
- src/main/java/com/yzgeneration/evc/domain/member/authentication/implement/AuthenticationProcessor.java
- src/main/java/com/yzgeneration/evc/domain/member/authentication/service/AuthenticationService.java
- src/test/java/com/yzgeneration/evc/docs/authentication/AuthenticationControllerDocsTest.java
- src/test/java/com/yzgeneration/evc/member/authentication/controller/AuthenticationControllerTest.java
- src/test/java/com/yzgeneration/evc/member/authentication/service/AuthenticationServiceTest.java
> [Refactor] 토큰 제공 방식 변경

- src/main/java/com/yzgeneration/evc/domain/verification/template/RegisterEmailVerificationTemplate.java
> [Fix] 이메일 요청 주소 수정

- src/main/java/com/yzgeneration/evc/domain/member/authentication/implement/AuthenticationProcessor.java
> [Fix] 쿠키 설정 변경

- .github/workflows/deploy.yml
> [Fix] deploy.yml 수정 2

- .github/workflows/deploy.yml
> [Fix] deploy.yml 수정 4

- .github/workflows/deploy.yml
> [Fix] deploy.yml 수정 5

- .github/workflows/deploy.yml
> [Fix] deploy.yml 수정 6

- .gitignore
> [Fix] deploy.yml 수정 7

- .github/workflows/deploy.yml
> git cache clean

- .github/workflows/deploy.yml
> [Fix] deploy.yml 수정 8

- .github/workflows/deploy.yml
> [Fix] deploy.yml 수정 9

- .github/workflows/deploy.yml
> [Fix] deploy.yml 수정 11

- .github/workflows/deploy.yml
> [Fix] deploy.yml 수정 12

- .github/workflows/deploy.yml
> [Fix] deploy.yml 수정 13

- .github/workflows/deploy.yml
> [Fix] deploy.yml 수정 14

- .github/workflows/deploy.yml
> [Fix] deploy.yml 수정 15

- .github/workflows/deploy.yml
> [Fix] deploy.yml 수정 16

- .github/workflows/deploy.yml
> [Fix] deploy.yml 수정 17

- .github/workflows/deploy.yml
> [Fix] deploy.yml 수정 18

- .github/workflows/deploy.yml
> [Fix] deploy.yml 수정 19

- .github/workflows/deploy.yml
> [Fix] deploy.yml 수정 20

- .github/workflows/deploy.yml
> [Fix] deploy.yml 수정 21

- .github/workflows/deploy.yml
> [Fix] deploy.yml 수정 22

- .github/workflows/deploy.yml
> [Fix] deploy.yml 수정 23

- .github/workflows/deploy.yml
> [Fix] deploy.yml 수정 24

- .github/workflows/deploy.yml
> [Fix] deploy.yml 수정 25

- .github/workflows/deploy.yml
> [Fix] deploy.yml 수정 27

- .github/workflows/deploy.yml
> [Fix] deploy.yml 수정 28

- .github/workflows/deploy.yml
> [Fix] deploy.yml 수정 29

- .github/workflows/deploy.yml
> [Fix] deploy.yml 수정 30

- .github/workflows/deploy.yml
> [Fix] deploy.yml 수정 31

- .github/workflows/deploy.yml
> [Fix] deploy.yml 수정 32

- .github/workflows/deploy.yml
> [Fix] deploy.yml 수정 34

- .github/workflows/deploy.yml
> [Fix] deploy.yml 수정 35

- .github/workflows/deploy.yml
> [Fix] deploy.yml 수정 36

- .github/workflows/deploy.yml
> [Fix] deploy.yml 수정 37

- src/main/java/com/yzgeneration/evc/domain/member/authentication/implement/AuthenticationProcessor.java
> [Fix] 쿠키 도메인 수정

- build.gradle
> [Chore] 액츄에이터 등록

- src/main/java/com/yzgeneration/evc/common/HealthCheckController.java
- src/main/java/com/yzgeneration/evc/security/JwtAuthenticationFilter.java
> [Chore] 헬스체크

- src/main/java/com/yzgeneration/evc/authentication/controller/AuthenticationController.java
- src/main/java/com/yzgeneration/evc/authentication/dto/AuthenticationRequest.java
- src/main/java/com/yzgeneration/evc/authentication/dto/AuthenticationResponse.java
- src/main/java/com/yzgeneration/evc/authentication/dto/AuthenticationToken.java
- src/main/java/com/yzgeneration/evc/authentication/implement/AuthenticationProcessor.java
- src/main/java/com/yzgeneration/evc/authentication/implement/TokenProvider.java
- src/main/java/com/yzgeneration/evc/authentication/infrastructure/RefreshTokenRepositoryImpl.java
- src/main/java/com/yzgeneration/evc/authentication/service/AuthenticationService.java
- src/main/java/com/yzgeneration/evc/authentication/service/port/RefreshTokenRepository.java
- src/main/java/com/yzgeneration/evc/domain/chat/implement/StompInterceptor.java
- src/test/java/com/yzgeneration/evc/docs/authentication/AuthenticationControllerDocsTest.java
- src/test/java/com/yzgeneration/evc/fixture/MemberFixture.java
- src/test/java/com/yzgeneration/evc/member/authentication/controller/AuthenticationControllerTest.java
- src/test/java/com/yzgeneration/evc/member/authentication/service/AuthenticationServiceTest.java
- src/test/java/com/yzgeneration/evc/mock/authentication/FakeRefreshTokenRepository.java
> [Refactor] 패키지변경

- src/main/java/com/yzgeneration/evc/domain/useditem/controller/UsedItemController.java
- src/main/java/com/yzgeneration/evc/domain/useditem/dto/UsedItemRequest.java
- src/main/java/com/yzgeneration/evc/domain/useditem/implement/UsedItemAppender.java
- src/main/java/com/yzgeneration/evc/domain/useditem/model/UsedItem.java
- src/main/java/com/yzgeneration/evc/domain/useditem/service/UsedItemService.java
- src/test/java/com/yzgeneration/evc/docs/usedItem/UsedItemControllerDocsTest.java
- src/test/java/com/yzgeneration/evc/usedItem/controller/UsedItemControllerTest.java
- src/test/java/com/yzgeneration/evc/usedItem/model/UsedItemTest.java
- src/test/java/com/yzgeneration/evc/usedItem/service/UsedItemServiceTest.java
> [Refactor] refactor/#107 내용 빠꾸 #109

- src/main/java/com/yzgeneration/evc/authentication/implement/AuthenticationProcessor.java
> [Refactor] 리다이렉트 주소 https 변경

- src/docs/asciidoc/chat/chat.adoc
- src/docs/asciidoc/index.adoc
> [Chore] api 문서 추가

- .github/issue-branch.yml
> issue branch test

- src/main/java/com/yzgeneration/evc/security/JwtAuthenticationFilter.java
> [Fix] 필터 경로 수정

- src/main/java/com/yzgeneration/evc/common/dto/SliceResponse.java
- src/main/java/com/yzgeneration/evc/config/WebSocketConfig.java
- src/main/java/com/yzgeneration/evc/domain/chat/controller/ChatController.java
- src/main/java/com/yzgeneration/evc/domain/chat/implement/ChatMessageListener.java
- src/main/java/com/yzgeneration/evc/domain/chat/infrastructure/ChatMessageRepository.java
- src/main/java/com/yzgeneration/evc/domain/chat/infrastructure/ChatMessageRepositoryImpl.java
- src/main/java/com/yzgeneration/evc/domain/chat/infrastructure/ChatRoomEntity.java
- src/main/java/com/yzgeneration/evc/domain/chat/service/ChatService.java
- src/main/java/com/yzgeneration/evc/security/StompInterceptor.java
> [Refactor] 채팅

- src/main/java/com/yzgeneration/evc/common/dto/SliceResponse.java
- src/main/java/com/yzgeneration/evc/domain/chat/dto/ChatRoomListResponse.java
- src/test/java/com/yzgeneration/evc/chat/controller/ChatControllerTest.java
- src/test/java/com/yzgeneration/evc/docs/chat/ChatControllerDocsTest.java
- src/test/java/com/yzgeneration/evc/mock/chat/FakeChatMessageRepository.java
> [Test] 테스트코드 수정

- src/main/java/com/yzgeneration/evc/config/WebSocketConfig.java
- src/main/java/com/yzgeneration/evc/domain/chat/controller/ChatController.java
- src/main/java/com/yzgeneration/evc/domain/chat/infrastructure/ChatMessageDocument.java
- src/main/java/com/yzgeneration/evc/domain/chat/infrastructure/ChatMessageRepository.java
- src/main/java/com/yzgeneration/evc/domain/chat/infrastructure/ChatMessageRepositoryImpl.java
- src/main/java/com/yzgeneration/evc/domain/chat/service/ChatService.java
- src/main/java/com/yzgeneration/evc/exception/CustomExceptionHandler.java
- src/main/java/com/yzgeneration/evc/exception/ErrorCode.java
- src/main/java/com/yzgeneration/evc/exception/StompThrowableHandler.java
- src/test/java/com/yzgeneration/evc/chat/controller/ChatControllerTest.java
- src/test/java/com/yzgeneration/evc/docs/chat/ChatControllerDocsTest.java
- src/test/java/com/yzgeneration/evc/mock/chat/FakeChatMessageRepository.java
close #
---
- 몽고DB atlas 사용에서 ec2에 직접 설치로 변경했습니다.
---
> 채팅 수정, 예외처리

- src/main/java/com/yzgeneration/evc/domain/chat/dto/ChatMessageResponse.java
- src/main/java/com/yzgeneration/evc/domain/chat/implement/ChatRoomManager.java
- src/main/java/com/yzgeneration/evc/domain/chat/infrastructure/ChatMessageRepositoryImpl.java
- src/test/java/com/yzgeneration/evc/chat/controller/ChatControllerTest.java
- src/test/java/com/yzgeneration/evc/docs/chat/ChatControllerDocsTest.java
- src/test/java/com/yzgeneration/evc/mock/chat/FakeChatMessageRepository.java
> [Feat] 채팅 전송이 정보 추가

- src/main/java/com/yzgeneration/evc/domain/chat/controller/ChatController.java
- src/main/java/com/yzgeneration/evc/domain/chat/dto/ChatMessageResponse.java
- src/main/java/com/yzgeneration/evc/domain/chat/infrastructure/ChatMessageRepository.java
- src/main/java/com/yzgeneration/evc/domain/chat/infrastructure/ChatMessageRepositoryImpl.java
- src/main/java/com/yzgeneration/evc/domain/chat/service/ChatService.java
- src/test/java/com/yzgeneration/evc/chat/controller/ChatControllerTest.java
- src/test/java/com/yzgeneration/evc/chat/service/ChatServiceTest.java
- src/test/java/com/yzgeneration/evc/docs/chat/ChatControllerDocsTest.java
- src/test/java/com/yzgeneration/evc/mock/chat/FakeChatMessageRepository.java
> [Feat] 본인소유 채팅인지 판별 여부 추가

- src/docs/asciidoc/authentication/authentication.adoc
- src/docs/asciidoc/chat/chat.adoc
- src/docs/asciidoc/point/point.adoc
> [Docs] api 문서 정리

- src/docs/asciidoc/chat/chat.adoc
- src/test/java/com/yzgeneration/evc/docs/chat/ChatControllerDocsTest.java
> [Docs] api 문서 추가

- src/main/java/com/yzgeneration/evc/application/event/MemberEventListener.java
- src/main/java/com/yzgeneration/evc/authentication/implement/AuthenticationProcessor.java
- src/main/java/com/yzgeneration/evc/config/AsyncConfig.java
- src/main/java/com/yzgeneration/evc/domain/image/infrastructure/entity/ProfileImageEntity.java
- src/main/java/com/yzgeneration/evc/domain/member/MemberCreatedEvent.java
- src/main/java/com/yzgeneration/evc/domain/member/infrastructure/EmailSender.java
- src/main/java/com/yzgeneration/evc/domain/member/model/MemberPrivateInformation.java
- src/main/java/com/yzgeneration/evc/domain/member/service/MemberRegisterService.java
- src/test/java/com/yzgeneration/evc/authentication/service/AuthenticationServiceTest.java
> [Feat] 소셜 로그인 시 프로필 이미지 가져오기

- src/main/java/com/yzgeneration/evc/domain/item/auctionitem/dto/AuctionBidResponse.java
- src/main/java/com/yzgeneration/evc/domain/item/auctionitem/dto/AuctionBidToListener.java
- src/main/java/com/yzgeneration/evc/domain/item/auctionitem/implement/AuctionBidListener.java
- src/main/java/com/yzgeneration/evc/domain/item/auctionitem/implement/AuctionBidProcessor.java
- src/main/java/com/yzgeneration/evc/domain/item/auctionitem/infrastructure/repository/AuctionItemRepositoryImpl.java
- src/main/java/com/yzgeneration/evc/domain/item/auctionitem/service/AuctionBidService.java
close #166 
---
-  경매시 경매자를 알 수 있도록 bidderId를 응답값에 포함
-  rabbitTemplate.convertAndSend의 routingKey 값 변경
---
> [Refactor/#166] 경매시 필요한 응답값 및 설정값 변경

- src/test/java/com/yzgeneration/evc/chat/model/ChatTest.java
- src/test/java/com/yzgeneration/evc/chat/service/ChatServiceTest.java
> [Test] 테스트 수정

- src/main/java/com/yzgeneration/evc/domain/chat/dto/Chatting.java
- src/main/java/com/yzgeneration/evc/domain/chat/service/ChatService.java
> [Refactor] 필드명 수정

- src/main/java/com/yzgeneration/evc/domain/chat/implement/ChatMessageListener.java
- src/main/java/com/yzgeneration/evc/domain/chat/service/ChatService.java
> [Fix] rabbitmq 예외 무한루프 임시 수정, 예외처리 필요

- src/main/java/com/yzgeneration/evc/domain/chat/dto/ChatMessageSliceResponse.java
- src/main/java/com/yzgeneration/evc/domain/chat/infrastructure/ChatMessageRepositoryImpl.java
- src/main/java/com/yzgeneration/evc/domain/chat/service/ChatService.java
- src/main/java/com/yzgeneration/evc/domain/item/auctionitem/infrastructure/repository/AuctionItemRepositoryImpl.java
- src/main/java/com/yzgeneration/evc/domain/item/auctionitem/service/port/AuctionItemRepository.java
- src/main/java/com/yzgeneration/evc/domain/item/useditem/infrastructure/repository/UsedItemRepositoryImpl.java
- src/main/java/com/yzgeneration/evc/domain/item/useditem/service/port/UsedItemRepository.java
- src/test/java/com/yzgeneration/evc/chat/controller/ChatControllerTest.java
- src/test/java/com/yzgeneration/evc/docs/chat/ChatControllerDocsTest.java
- src/test/java/com/yzgeneration/evc/mock/auctionitem/FakeAuctionItemRepository.java
- src/test/java/com/yzgeneration/evc/mock/chat/FakeChatMessageRepository.java
- src/test/java/com/yzgeneration/evc/mock/usedItem/FakeUsedItemRepository.java
> [Refactor] 채팅 api 본인 id 추가

- src/main/java/com/yzgeneration/evc/domain/chat/dto/Chatting.java
- src/main/java/com/yzgeneration/evc/domain/chat/dto/ChattingToListener.java
- src/main/java/com/yzgeneration/evc/domain/chat/implement/ChatMessageListener.java
- src/main/java/com/yzgeneration/evc/domain/chat/service/ChatService.java
> [Refactor] 채팅메시지 리스폰스 수정

- src/docs/asciidoc/auctionitem/auctionitem.adoc
- src/docs/asciidoc/usedItem/usedItem.adoc
- src/main/java/com/yzgeneration/evc/domain/item/auctionitem/controller/AuctionItemController.java
- src/main/java/com/yzgeneration/evc/domain/item/auctionitem/infrastructure/repository/AuctionItemRepositoryImpl.java
- src/main/java/com/yzgeneration/evc/domain/item/auctionitem/service/AuctionItemService.java
- src/main/java/com/yzgeneration/evc/domain/item/auctionitem/service/port/AuctionItemRepository.java
- src/main/java/com/yzgeneration/evc/domain/item/useditem/controller/UsedItemController.java
- src/main/java/com/yzgeneration/evc/domain/item/useditem/infrastructure/repository/UsedItemJpaRepository.java
- src/main/java/com/yzgeneration/evc/domain/item/useditem/infrastructure/repository/UsedItemRepositoryImpl.java
- src/main/java/com/yzgeneration/evc/domain/item/useditem/service/UsedItemService.java
- src/main/java/com/yzgeneration/evc/domain/item/useditem/service/port/UsedItemRepository.java
- src/test/java/com/yzgeneration/evc/docs/auctionitem/AuctionItemControllerDocsTest.java
- src/test/java/com/yzgeneration/evc/docs/usedItem/UsedItemControllerDocsTest.java
- src/test/java/com/yzgeneration/evc/mock/auctionitem/FakeAuctionItemRepository.java
- src/test/java/com/yzgeneration/evc/mock/usedItem/FakeUsedItemRepository.java
close #176 
---
- 상품 검색 기능 추가
---
<i>중고상품 검색</i>
<i>중고상품 검색</i>
> [Feat/#176] 상품 검색 기능

- src/docs/asciidoc/index.adoc
> [Docs] 문서 추가

- src/main/java/com/yzgeneration/evc/exception/ExternalApiExceptionV2.java
> [Refactor] 예외 리스폰스 수정

- src/main/java/com/yzgeneration/evc/domain/item/auctionitem/dto/AuctionItemsResponse.java
- src/main/java/com/yzgeneration/evc/domain/item/auctionitem/infrastructure/repository/AuctionItemRepositoryImpl.java
- src/main/java/com/yzgeneration/evc/domain/item/auctionitem/service/AuctionItemService.java
- src/main/java/com/yzgeneration/evc/domain/item/auctionitem/service/port/AuctionItemRepository.java
- src/test/java/com/yzgeneration/evc/auctionitem/controller/AuctionItemControllerTest.java
- src/test/java/com/yzgeneration/evc/docs/auctionitem/AuctionItemControllerDocsTest.java
- src/test/java/com/yzgeneration/evc/mock/auctionitem/FakeAuctionItemRepository.java
close #188 
---
- 경매 전체 조회시 카테고리 응답필드 추가
---
> [Refactor/#188] 경매 전체 조회시 카테고리 응답필드 추가

- src/main/java/com/yzgeneration/evc/authentication/controller/AuthenticationController.java
- src/main/java/com/yzgeneration/evc/authentication/implement/AuthenticationProcessor.java
- src/main/java/com/yzgeneration/evc/authentication/service/AuthenticationService.java
> [Feat] 로그아웃

- src/main/java/com/yzgeneration/evc/domain/chat/dto/ChatMessageSliceResponse.java
- src/main/java/com/yzgeneration/evc/domain/chat/dto/ChatRoomListMetadata.java
- src/main/java/com/yzgeneration/evc/domain/chat/dto/ChatRoomListResponse.java
- src/main/java/com/yzgeneration/evc/domain/chat/dto/ChatRoomMetaData.java
- src/main/java/com/yzgeneration/evc/domain/chat/infrastructure/ChatMessageRepositoryImpl.java
- src/main/java/com/yzgeneration/evc/domain/chat/service/ChatService.java
- src/main/java/com/yzgeneration/evc/domain/delivery/impl/DeliveryProcessor.java
- src/main/java/com/yzgeneration/evc/domain/delivery/model/Delivery.java
- src/main/java/com/yzgeneration/evc/domain/delivery/model/DeliveryStatus.java
- src/main/java/com/yzgeneration/evc/domain/delivery/service/DeliveryService.java
- src/test/java/com/yzgeneration/evc/chat/controller/ChatControllerTest.java
- src/test/java/com/yzgeneration/evc/docs/chat/ChatControllerDocsTest.java
- src/test/java/com/yzgeneration/evc/mock/chat/FakeChatMessageRepository.java
> [Refactor] 채팅방 조회 / 채팅목록 조회 리턴 필드 추가

- src/main/java/com/yzgeneration/evc/domain/chat/dto/ChatMessageSliceResponse.java
- src/main/java/com/yzgeneration/evc/domain/chat/infrastructure/ChatMessageRepositoryImpl.java
- src/test/java/com/yzgeneration/evc/chat/controller/ChatControllerTest.java
- src/test/java/com/yzgeneration/evc/docs/chat/ChatControllerDocsTest.java
- src/test/java/com/yzgeneration/evc/mock/chat/FakeChatMessageRepository.java
> [Refactor] 누락 필드 추가

- src/main/java/com/yzgeneration/evc/domain/item/auctionitem/infrastructure/entity/AuctionItemEntity.java
- src/main/java/com/yzgeneration/evc/domain/item/auctionitem/model/AuctionItem.java
close #197
---
- 경매 도메인에 TransactionMode 필드 추가
---
> [Refactor] 경매 도메인에 TransactionMode 필드 추가 #197

- src/main/java/com/yzgeneration/evc/domain/point/controller/PointChargeController.java
> [Feat] 웹훅 테스트

- src/docs/asciidoc/my/my.adoc
- src/main/java/com/yzgeneration/evc/domain/image/implement/ItemImageUpdater.java
- src/main/java/com/yzgeneration/evc/domain/image/infrastructure/repository/ItemImageRepositoryImpl.java
- src/main/java/com/yzgeneration/evc/domain/image/service/port/ItemImageRepository.java
- src/main/java/com/yzgeneration/evc/domain/item/auctionitem/dto/AuctionItemResponse.java
- src/main/java/com/yzgeneration/evc/domain/item/auctionitem/infrastructure/repository/AuctionItemRepositoryImpl.java
- src/main/java/com/yzgeneration/evc/domain/item/auctionitem/model/AuctionItem.java
- src/main/java/com/yzgeneration/evc/domain/item/auctionitem/model/AuctionItemDetails.java
- src/main/java/com/yzgeneration/evc/domain/item/auctionitem/model/AuctionItemPriceDetails.java
- src/main/java/com/yzgeneration/evc/domain/item/useditem/model/ItemDetails.java
- src/main/java/com/yzgeneration/evc/domain/item/useditem/model/UsedItem.java
- src/main/java/com/yzgeneration/evc/domain/item/useditem/model/UsedItemTransaction.java
- src/main/java/com/yzgeneration/evc/domain/my/controller/MyStoreController.java
- src/main/java/com/yzgeneration/evc/domain/my/dto/MyAuctionItemUpdateRequest.java
- src/main/java/com/yzgeneration/evc/domain/my/dto/MyUsedItemUpdateRequest.java
- src/main/java/com/yzgeneration/evc/domain/my/implement/MyItemUpdater.java
- src/main/java/com/yzgeneration/evc/domain/my/service/MyStoreService.java
- src/test/java/com/yzgeneration/evc/auctionitem/controller/AuctionItemControllerTest.java
- src/test/java/com/yzgeneration/evc/docs/auctionitem/AuctionItemControllerDocsTest.java
- src/test/java/com/yzgeneration/evc/docs/my/MyStoreControllerDocsTest.java
- src/test/java/com/yzgeneration/evc/mock/auctionitem/FakeAuctionItemRepository.java
- src/test/java/com/yzgeneration/evc/mock/image/FakeItemImageRepository.java
close #210 
---
- 내 중고상품 수정
- 내 경매상품 수정
---
> [Feat/#210] 내 상품 수정 기능 추가

- src/main/java/com/yzgeneration/evc/domain/like/controller/LikeController.java
- src/main/java/com/yzgeneration/evc/domain/like/implement/LikeReader.java
- src/main/java/com/yzgeneration/evc/domain/like/infrastructure/repository/LikeRepositoryImpl.java
- src/main/java/com/yzgeneration/evc/domain/like/service/LikeService.java
- src/main/java/com/yzgeneration/evc/domain/like/service/port/LikeRepository.java
- src/test/java/com/yzgeneration/evc/docs/auctionitem/AuctionItemControllerDocsTest.java
- src/test/java/com/yzgeneration/evc/docs/like/LikeControllerDocsTest.java
- src/test/java/com/yzgeneration/evc/docs/member/MemberStoreControllerDocsTest.java
- src/test/java/com/yzgeneration/evc/docs/my/MyStoreControllerDocsTest.java
- src/test/java/com/yzgeneration/evc/docs/usedItem/UsedItemControllerDocsTest.java
- src/test/java/com/yzgeneration/evc/mock/like/FakeLikeRepository.java
close #213 
---
- 내 좋아요 상품 조회시 cursor 쿼리 파라미터를 이용하도록 변경
---
> [Refactor/#213] 내 좋아요 상품 조회시 cursor 쿼리 파라미터를 이용하도록 변경

- src/main/java/com/yzgeneration/evc/domain/item/auctionitem/dto/AuctionItemResponse.java
- src/main/java/com/yzgeneration/evc/domain/item/auctionitem/dto/AuctionItemsResponse.java
- src/main/java/com/yzgeneration/evc/domain/item/auctionitem/infrastructure/repository/AuctionItemRepositoryImpl.java
- src/main/java/com/yzgeneration/evc/domain/item/useditem/controller/UsedItemController.java
- src/main/java/com/yzgeneration/evc/domain/item/useditem/dto/UsedItemResponse.java
- src/main/java/com/yzgeneration/evc/domain/item/useditem/dto/UsedItemsResponse.java
- src/main/java/com/yzgeneration/evc/domain/item/useditem/implement/UsedItemReader.java
- src/main/java/com/yzgeneration/evc/domain/item/useditem/infrastructure/repository/UsedItemRepositoryImpl.java
- src/main/java/com/yzgeneration/evc/domain/item/useditem/service/UsedItemService.java
- src/main/java/com/yzgeneration/evc/domain/item/useditem/service/port/UsedItemRepository.java
- src/test/java/com/yzgeneration/evc/auctionitem/controller/AuctionItemControllerTest.java
- src/test/java/com/yzgeneration/evc/docs/auctionitem/AuctionItemControllerDocsTest.java
- src/test/java/com/yzgeneration/evc/docs/usedItem/UsedItemControllerDocsTest.java
- src/test/java/com/yzgeneration/evc/mock/auctionitem/FakeAuctionItemRepository.java
- src/test/java/com/yzgeneration/evc/mock/usedItem/FakeUsedItemRepository.java
- src/test/java/com/yzgeneration/evc/usedItem/controller/UsedItemControllerTest.java
- src/test/java/com/yzgeneration/evc/usedItem/service/UsedItemServiceTest.java
close #215 
---
- 상품 개별 조회시 상품주인의 프로필 사진 조회
- 상품 전체 조회시 내 좋아요 여부 표시
---
> [Refactor/#215] 상품 개별 조회시 상품주인의 프로필 사진 조회 & 상품 전체 조회시 내 좋아요 여부 표시

- src/main/java/com/yzgeneration/evc/application/event/MemberEventListener.java
- src/main/java/com/yzgeneration/evc/domain/member/service/MemberRegisterService.java
> [Fix] 이벤트 처리 정상화
